### ISSUE TITLE
Install pip error

### ISSUE THREAD

**Issue by damientully** [wdecoster/nanoretrotect#1]
` pip install nanoretrotect`
`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qf/xyw13rmn5_12v4d64rzh6lpc0000gn/T/pip-build-pwy0y52f/nanoretrotect/
`

**Comment by wdecoster** [comment]
That's a cryptic error message. Are you using Python3 and a recent pip version?

**Comment by damientully** [comment]
Yes using Python 3.6.3. See below

```
pip install nanoretrotect
Collecting nanoretrotect
  Using cached nanoretrotect-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qf/xyw13rmn5_12v4d64rzh6lpc0000gn/T/pip-build-axjqq221/nanoretrotect/setup.py", line 10, in <module>
        exec(open('nanoretrotect/version.py').read())
      File "/Users/damientully/anaconda3/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'nanoretrotect/version.py'
```

**Comment by wdecoster** [comment]
Oh, adding the full error message makes things a lot clearer. I'll create a version 0.1.1 in a few minutes, seems I forgot to package the version.py file. I guess that's what you get if you test insufficiently :)

**Comment by wdecoster** [comment]
nanoretrotect version 0.1.1 is up (and installation this time tested on a different server)

Make sure to use the following flag with pip to get the latest version.

`pip install nanoretrotect --no-cache-dir`

 I've added the example plot of my test dataset below.


![cumulativeyieldplot_numberofreads](https://user-images.githubusercontent.com/11660522/35100541-7c49bd3a-fc5c-11e7-92a3-1b961b06e479.png)

**Comment by damientully** [comment]
Thanks Wouter. Updated and installed now. 

nanoretrotect --bam BC08.sorted.bam --summary sequencing_summary.txt  

Seem to be getting an error which could be related to the bam file
> Traceback (most recent call last):
>   File "/Users/damientully/anaconda3/bin/nanoretrotect", line 11, in <module>
>     load_entry_point('nanoretrotect==0.1.1', 'console_scripts', 'nanoretrotect')()
>   File "/Users/damientully/anaconda3/lib/python3.6/site-packages/nanoretrotect/nanoretrotect.py", line 23, in main
>     hours=args.hours)
>   File "/Users/damientully/anaconda3/lib/python3.6/site-packages/nanoretrotect/nanoretrotect.py", line 91, in plot_retrotect
>     warning=False)
> TypeError: check_valid_time_and_sort() got an unexpected keyword argument 'warning'

**Comment by wdecoster** [comment]
Oops, sorry for the mess. I forgot to specify a dependency for nanoretrotect, and in version 0.1.2 that should be fixed, which I just pushed to PyPI.  This is getting a bit embarrassing, let's hope this is the last mistake.

**Comment by damientully** [comment]
Thanks! Its fixed. One question about the x axis. Is the scale cutoff determined by the sequencing summary file? As If I have a run that ran for 48hrs should I expect the scale to ~2800 mins?

**Comment by wdecoster** [comment]
By default, the first 8 hours are plotted, but you can adapt that using the `--hours` parameter.

**Comment by damientully** [comment]
Sorry I see if I change the hours option then the scale changes so the default is set to 500

**Comment by damientully** [comment]
Nice..this looks great! Is there an option to perhaps print the details to file or something like that?

**Comment by wdecoster** [comment]
Which details, exactly?

**Comment by damientully** [comment]
Good question! Hmm... I guess essentially the constituents of the plot as in reads numbers binned per hour etc..? Just so one could quantify the details more as in X% of reads were detected within 60 mins. The other option would be just to print the aligned read details as in read name and time.

**Comment by wdecoster** [comment]
Anything is possible. I'm not going to think too much about this, so you just have to tell me which details are (most) useful/desirable.

**Comment by damientully** [comment]
Thanks Wouter. I guess as an option if you are able to print out the raw graph details to a file as in
ReadName Time

This way the user could parse this file in whatever way they wanted. 
Sorry, does that make any sense to you?

**Comment by wdecoster** [comment]
Sure, so for every aligned read you get the read identifier and the time when that read started sequencing. Very well, I'll add it and create a new version in a few minutes.

**Comment by wdecoster** [comment]
version 0.2.0 is up, which will create a Retrotect_details.txt.gz file containing readIDs and their start of sequencing.

I'm going to close this thread now. Please let me know (in a new issue) if you have other ideas on how to improve nanoretrotect.
