### ISSUE TITLE
Plot scale issue

### ISSUE THREAD

**Issue by damientully** [wdecoster/nanoretrotect#2]
Hi Wouter,

I'm not sure if there is an issue with the scale on the plots. See attached files. As you can see there should be close to 200 reads within the first 60 mins according to the file but the plot is very different.

[Retrotect_details 3.txt](https://github.com/wdecoster/nanoretrotect/files/1643453/Retrotect_details.3.txt)
![cumulativeyieldplot_numberofreads](https://user-images.githubusercontent.com/17030873/35106972-b14cf5c0-fc3d-11e7-845d-1b5a49ee5c3c.png)

**Comment by wdecoster** [comment]
You are right, that doesn't look okay. I'll investigate!

**Comment by wdecoster** [comment]
Ya, that was a pretty damn ridiculous mistake I made. Should be fixed in 0.3.0.

Thanks for your feedback!

**Comment by damientully** [comment]
Great....looks fixed!

Thanks again Wouter!
